### ISSUE TITLE
No such file or directory: './scripts/vgg16.npy'

### ISSUE THREAD

**Issue by gaoxurong** [VerseChow/SegNet_tensorflow#1]
Hi，I have meet such problrm “No such file or directory: './scripts/vgg16.npy'".Please give some advice.

**Comment by VerseChow** [comment]
Hi, sorry for late reply. vgg16.npy is a pretrained model and it is so large so that I didn't push that. Please see https://github.com/machrisaa/tensorflow-vgg  README File to download it and put it to script. Thanks!

**Comment by gaoxurong** [comment]
Thank you！I will have a try.
